### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by actuallylost** [maikkundev/digapictures-website#1]
This is going to add the ability to run the entire project inside docker containers.

## TODO
- [ ] Update Docker Comppose file to contain the three services.
- [x] Add the Postgres DB service
- [ ] Add Dockerfile for API service
- [ ] Add Dockerfile for Frontend Service
